@TaskManager_HostAddress = http://localhost:5219
//Is it alive?
GET {{TaskManager_HostAddress}}/api/ping
###

//Testing Job Controller
GET {{TaskManager_HostAddress}}/api/jobs/
Accept: application/json
###

GET {{TaskManager_HostAddress}}/api/jobs/2
Accept: application/json
###

GET {{TaskManager_HostAddress}}/api/jobs?assignedToUserId=1&excludeDone=true&dueInDays=7
###

GET {{TaskManager_HostAddress}}/api/jobs/search?title=App
Accept: application/json
###

POST {{TaskManager_HostAddress}}/api/jobs
Content-Type: application/json
Accept: application/json

{
    "title": "Implement authentication",
    "status": 0,
    "priority": 2,
    "createdAt": "2025-10-21T12:00:00Z",
    "dueDate": "2025-10-25T12:00:00Z",
    "assignedToUserId": 2,
    "projectId": 1,
    "creatorId": 1
}
###

//Testing Project Controller

GET {{TaskManager_HostAddress}}/api/projects/
Accept: application/json
###

GET {{TaskManager_HostAddress}}/api/projects/2
Accept: application/json
###

GET {{TaskManager_HostAddress}}/api/projects/search?name=App
Accept: application/json
###


POST {{TaskManager_HostAddress}}/api/projects
Content-Type: application/json
{
  "name": "New Marketing Campaign",
  "description": "Launch a new social media campaign",
  "createdBy": 2
}
###

PUT {{TaskManager_HostAddress}}/api/projects/3
Content-Type: application/json
{
  "id": 3,
  "name": "Updated Marketing Campaign",
  "description": "Launch an updated social media campaign",
  "createdBy": 2
}
###